### PR TITLE
Sort featured news

### PR DESCRIPTION
**Pull request by xchs**
Add a new sorting option for featured news.

### CODE REVIEW

**Comment by xchs** [comment]
Would you consider this a new core feature as well after all the other sorting methods have already been available as of Contao 4.5 (see https://github.com/contao/news-bundle/pull/13)?

**Comment by fritzmg** [comment]
Sure, why not :). This enables you to have one newslist module instead of two, in some situations. Can you create a PR for the news-bundle as well?

**Comment by xchs** [comment]
> This enables you to have one newslist module instead of two

Yeah, that's exactly the reason why I thought it might be useful.

I have created a pull request for the `contao/news-bundle`, too: https://github.com/contao/contao/pull/371

**Comment by fritzmg** [comment]
Nice. I will merge this soon and also make some improvements, to be able to use it in Contao 4.5+

**Comment by fritzmg** [comment]
thank you @xchs

**Comment by fritzmg** [comment]
I have released `1.2.0` which includes your changes. As announced, I have added additional compatibility code so that this extension can be seamlessly used in any Contao 4 version. The hook is only used when necessary.

**Comment by xchs** [comment]
Thank you. 👍

**Pull request merged**
